version: "3.9"
services:
  bot:
    build: .
    ports:
      # Expose Prometheus metrics (you need to also enable them in the config)
      - "8000:8000"
    environment:
      - LOGLEVEL=INFO
    volumes:
      - ./config.yml:/app/config.yml
      # - ./src/main.py:/app/src/main.py
    restart: always
