version: "3.9"
services:
  bot:
    image: anxolin/eth2-monitor:latest
    ports:
      # Expose Prometheus metrics (you need to also enable them in the config)
      - "8000:8000"
    environment:
      - LOGLEVEL=INFO
    volumes:
      - ./config.yml:/app/config.yml
    restart: always
